#!/bin/sh
# Used to test chname
name=`basename $0`

create_subdir_n_deep(){
    #unfinished, only creates the directories
#    i in `seq 1 $dir_deep`
    i=0
    create_dir_name="$dir_name$i"
    prog="test_prog"

    while test $i != $dir_deep
        do
        mkdir $create_dir_name
        create_example_files
        i=$((i + 1)) #increments i
        create_dir_name="$create_dir_name/$dir_name$i"     
        
    done
    
}
create_example_files(){
    touch "$create_dir_name/UPPERCASE%#$.txt"
    touch "$create_dir_name/l0werc@se!.cpp"
    touch "$create_dir_name/S0m3_LoWer!sOmE_UpPer"

}
hold_remove(){
    read -p "Press enter to continue" enter_key
    echo
    echo "Deleting directories and files created"
    echo
    if test $case_option = "u"
    then
        rm -r "$(echo "$dir_name$zero" | tr '[:lower:]' '[:upper:]')"
    else
        rm -r "$(echo "$dir_name$zero" | tr '[:upper:]' '[:lower:]')"
    fi

    echo " Directories and files deleted"
    echo
}

case_option(){
    read -p "Enter 'u' for UPPERCASE or 'l' for lowercase: " case_option

    case "$case_option" in
        u|U) case_option='u';;
        l|L) case_option='l';;
        *) echo "Invalid option. Defaulting to lowercase."
            case_option='l';;
    esac
}

display_result() {
    if [ $1 -eq 0 ]; then
        echo "[PASS] $2"
    else
        echo "[FAIL] $2"
    fi
}

if test "$1" 
then 
echo "This program doesn't require any arguments, it will test everything and wait for the users signal to continue\n"; 
exit 1; 
fi
clear
echo "          Testing ./chname -h"

./chname -h

read -p "Press enter to continue" enter_key
clear

#Tests error messages
echo "          Testing error messages"

echo "\nWith no input name given ./chname -l test\n"
./chname -l
read -p "Press enter to continue" enter_key
clear

echo "\nWith both -u and -l arguments ./chname -u -l test:\n"
./chname -u -l test

echo "\n-r with no -s ./chname -r -l test\n"
./chname -r -l test

echo "\nWith invalid option ./chname -z test\n"
./chname -z test

echo "\nWith no arguments ./chname\n"
./chname

read -p "Press enter to continue" enter_key
clear

echo "\nWith inexistent file 'test' ./chname -l test\n"
./chname -l test
echo "\n Message is the same for only one existent file or a list of them mixed with inexistent files\n"

read -p "Press enter to continue" enter_key
clear

echo "\nWith inexistent directory 'test' ./chname -l test\n"
./chname -l -s test
touch test
echo "\nWith file but -s argument ./chname -s test\n"
./chname -s test
rm test
echo "\nThere is also a warning for when a file is skipped because of it alreadt being uppercase or lower case which will be seen shortly\n"

read -p "Press enter to continue" enter_key
clear
#Tests uppercase and lowercase
touch 'UPPERCASE%#$.txt'
touch 'l0werc@se!'

echo "Testing uppercase, argument -u and lowercase, argument -l\n"

echo "------------------- ls before running ./chname -$case_option $dir_name$zero -------------------\n"
ls 
./chname -l UPPERCASE%#$.txt
./chname -u l0werc@se!
echo "------------------- ls  after running ./chname -$case_option $dir_name$zero -------------------\n"
ls 

read -p "Press enter to continue" enter_key
rm -r "$(echo "UPPERCASE%#$.txt" | tr '[:upper:]' '[:lower:]')"
rm -r "$(echo "l0werc@se!" | tr '[:lower:]' '[:upper:]')"
clear

#Tests recursive
zero='0'
dir_deep=3
dir_name="testRecursive"
file_name="$dir_name.txt"
create_dir_name='.'
create_subdir_n_deep

echo "Testing recursive, argument -r\n"
case_option

echo "------------------- ls -R before running ./chname -r -s -$case_option $dir_name$zero -------------------\n"
ls -R -r
echo "\nchname warning messages\n"
./chname -r -s -$case_option "$dir_name$zero" 

echo "------------------- ls -R after running ./chname -r -s -$case_option $dir_name$zero -------------------\n"
ls -R -r

hold_remove
clear
#tests subdirectories
dir_deep=1
dir_name="testSubdir"
create_dir_name='.'
create_subdir_n_deep

echo "Testing subdirectories, argument -s\n"
case_option

echo "------------------- ls -R before running ./chname -s -$case_option $dir_name$zero -------------------\n"
ls -R

echo "\nchname warning messages\n"

./chname -s -$case_option $dir_name$zero

echo "'\n'------------------- ls -R after running ./chname -s -$case_option $dir_name$zero -------------------\n"
ls -R

hold_remove
echo
